apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  destination:
    namespace: kyverno
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 2.6.0