apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true     
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: "2.7.0"