apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tanmay-bhat/gitops-demo.git'
    path: clusters/gitops-cluster/kubernetes-manifests/nginx-server
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true