apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: "15.16.0"
    helm:
      values: |
        serviceAccounts:
          alertmanager:
            create: false
          nodeExporter:
            create: false
          pushgateway:
            create: false
          server:
            create: false
        alertmanager:
          ## If false, alertmanager will not be installed
          ##
          enabled: false
        kubeStateMetrics:
          ## If false, kube-state-metrics sub-chart will not be installed
          ##
          enabled: false
        nodeExporter:
          ## If false, node-exporter will not be installed
          ##
          enabled: false
        prometheus:
        pushgateway:
          ## If false, pushgateway will not be installed
          ##
          enabled: false
        serverFiles:
          prometheus.yml:
            scrape_configs:
              - job_name: nginx
                scrape_interval: 5s          
                static_configs:
                  - targets: ['nginx:9113']