apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-scale
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: 'https://github.com/tanmay-bhat/gitops.git'
    path: clusters/gitops-cluster/kubernetes-manifests/keda
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
